services:
  db:
    image: library/postgres:13-alpine
    environment:
      POSTGRES_DB: expenses
      POSTGRES_USER: darwinai
      POSTGRES_PASSWORD: darwinai
    volumes:
      - pgdata2:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  pgdata2:
